events {}

http {
    map $cookie_session_id $session_fingerprint {
        "~^(?<fingerprint>.{8})" $fingerprint;
        default "-";
    }

    log_format main '$remote_addr $time_iso8601 "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_host" '
                    '"$http_user_agent" '
                    '$ssl_protocol '
                    '$session_fingerprint '
                    '"$http_x_forwarded_for" '
                    '$request_time ';
    access_log /var/log/nginx/access.log main;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;
        listen 443 ssl;

        server_name localhost;

        ssl_certificate /etc/nginx/ssl/localhost.pem;
        ssl_certificate_key /etc/nginx/ssl/localhost.key;

        location / {
            proxy_pass http://host.containers.internal:8069;
        }

        location /longpolling/ {
            proxy_http_version 1.1;
            proxy_pass http://host.containers.internal:8072;
        }

        location /websocket {
            proxy_http_version 1.1;
            proxy_pass http://host.containers.internal:8072;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}
