version: '3.7'
services:
  odoo:
    build:
      context: .
      dockerfile: "${DOCKERFILE}.dockerfile"
    image: "odoo-ready:${DOCKERFILE}"
    volumes:
      - "./bin/entrypoint:/usr/local/bin/entrypoint:ro"
      - "./bin/odoo:/usr/local/bin/odoo:ro"
      - "~/src/odoo:/home/odoo/src/odoo:ro"
      - "~/src/enterprise:/home/odoo/src/enterprise:ro"
      - "~/src/upgrade:/home/odoo/src/upgrade:ro"
      - "~/src/upgrade-util:/home/odoo/src/upgrade-util:ro"
      - "/var/run/postgresql:/var/run/postgresql:ro"
    entrypoint: entrypoint
    command: odoo
    environment:
      USER: ${USER}
      UID: ${USER_ID}
    cap_add:
      - NET_ADMIN
      - NET_RAW
