services:
  squid:
    container_name: squid
    image: docker.io/ubuntu/squid:latest
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./squid/whitelist.txt:/etc/squid/whitelist.txt
    networks:
      - internal
      - internet

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: "images/postgres.dockerfile"
    image: "localhost/postgres"
    environment:
      - POSTGRES_PASSWORD=unused-but-required-for-init-will-be-deleted-with-init-script-remove-superuser-password.sql
      - POSTGRES_INITDB_ARGS=--auth-local=peer --auth-host=scram-sha-256
    volumes:
      - postgres-data:/var/lib/postgresql
      - postgres-socket:/var/run/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

  odoo:
    build:
      context: .
      dockerfile: "images/${DOCKERFILE:-trixie}.dockerfile"
    image: "localhost/odoo:${DOCKERFILE:-trixie}"
    user: odoo
    environment:
      - DISPLAY=${DISPLAY}
      - HTTP_PROXY=http://squid:3128
      - HTTPS_PROXY=http://squid:3128
      - NO_PROXY=localhost,127.0.0.1,squid
      - ODOO_SRC=/home/$USER/src/
    volumes:
      - postgres-socket:/var/run/postgresql
      - odoo-local:/home/odoo/.local
      - ~/src/odoo:/home/$USER/src/odoo
      - ~/src/enterprise:/home/$USER/src/enterprise
      - ~/src/design-themes:/home/$USER/src/design-themes
      - ~/src/upgrade:/home/$USER/src/upgrade
      - ~/src/upgrade-util:/home/$USER/src/upgrade-util
      - ./bin/odoo:/usr/local/bin/odoo:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    networks:
      - internal

volumes:
  postgres-data:
  postgres-socket:
  odoo-local:

networks:
  internal:
    internal: true
  internet:
    driver: bridge

x-podman:
    in_pod: false  # See https://github.com/containers/podman-compose/pull/964
