services:
  codex:
    extends:
      service: odoo
    build:
      dockerfile: "images/${DOCKERFILE:-trixie}-codex.dockerfile"
    image: "localhost/odoo:${DOCKERFILE:-trixie}-codex"

    volumes:
      - ./.codex/home:/home/$USER/.codex:Z
      - ./.codex/workspace:/workspace:Z

    environment:
      CODEX_HOME: /home/$USER/.codex
      WT_SESSION: $WT_SESSION  # To support codex pets in Windows Terminal, very important

    working_dir: /workspace
