services:
  odoo:
    build:
      dockerfile: "images/${DOCKERFILE}-codex.dockerfile"
    image: "localhost/odoo:${DOCKERFILE}-codex"

    volumes:
      - ./.codex/home:/home/odoo/.codex:Z
      - ./.codex/workspace:/home/odoo/workspace:Z

    environment:
      CODEX_HOME: /home/odoo/.codex

    working_dir: /home/odoo/workspace
