services:
  squid:
    container_name: squid
    image: ubuntu/squid:latest
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./squid/whitelist.txt:/etc/squid/whitelist.txt
    networks:
      - internal
      - internet

  odoo:
    build:
      context: .
      dockerfile: "images/${DOCKERFILE}.dockerfile"
    image: "localhost/odoo:${DOCKERFILE}"
    userns_mode: "keep-id"  # To keep same UID/GID as host, mainly for the postgresql sockect connection
    environment:
      - HOME=/home/$USER/
      - DISPLAY=${DISPLAY}
      - HTTP_PROXY=http://squid:3128
      - HTTPS_PROXY=http://squid:3128
      - NO_PROXY=localhost,127.0.0.1,squid
    volumes:
      - ~/.local/share/docker-odoo-ready/home:/home/$USER
      - ~/src/odoo:/home/$USER/src/odoo
      - ~/src/enterprise:/home/$USER/src/enterprise
      - ~/src/design-themes:/home/$USER/src/design-themes
      - ~/src/upgrade:/home/$USER/src/upgrade
      - ~/src/upgrade-util:/home/$USER/src/upgrade-util
      - ./bin/odoo:/usr/local/bin/odoo:ro
      - /var/run/postgresql:/var/run/postgresql:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    networks:
      - internal

networks:
  internal:
    internal: true
  internet:
    driver: bridge

x-podman:
    in_pod: false  # See https://github.com/containers/podman-compose/pull/964
