services:
  codex:
    extends:
      service: odoo
    build:
      dockerfile: "images/${DOCKERFILE:-trixie}-codex.dockerfile"
    image: "localhost/odoo:${DOCKERFILE:-trixie}-codex"

    volumes:
      - codex-home:/home/$USER/.codex
      - codex-workspace:/workspace
      - ~/Downloads/codex-documents:/workspace/documents

    environment:
      CODEX_HOME: /home/$USER/.codex
      WT_SESSION: $WT_SESSION  # To support codex pets in Windows Terminal, very important

    working_dir: /workspace

    command:
      - codex
      - --ask-for-approval
      - never
      - --sandbox
      - danger-full-access

volumes:
  codex-home:
  codex-workspace:
